### ISSUE TITLE
[TRACKING] Build system issues

### ISSUE THREAD

**Issue by levex** [nanovms/nanos#196]
- [x] Parallel build
- [x] Proper `.c` file dependencies (Issue #195)
- [x] Proper `.h` file dependencies (makedep?)
- [x] Make it possible to add more parameters to Qemu command line easily (aka the current `DEBUG=y`)
- [x] Fix #31 (qemu using two images due to file locking)
- [x] Add clang support (Issue #193)
