### ISSUE TITLE
ruby hello world

### ISSUE THREAD

**Issue by eyberg** [nanovms/nanos#335]
- [x] #286 - pipe(2) - not sure if this can be closed or needs more work?
- [x] #281 - ??
- [x] ~~pretty sure both python && ruby want something for locale/encoding - we see a lot of issues w/that~~
- [x] nanovms/ops#84 - mkfs issue (both ruby/python include a *ton* of /usr/lib crap and mkfs segfaults sometimes
- [x] #405 - missing fcntl support - both python/ruby have been puking on this
- [x] #426 - fix reading into malloc'ed buffer
- [x] #432 - reader is not unblocked when pipe write end is closed - this causes blocking on ruby exit (cleanup)
