### ISSUE TITLE
infrastructure provisioning roll-up

### ISSUE THREAD

**Issue by eyberg** [nanovms/nanos#336]
before diving into anything I'd like to confirm precisely what each provider is going to want and also keep in mind that depending on which provider you are deploying to we might have different booting methods

- [x] ~~https://github.com/nanovms/nanos/issues/273 - boot with grub~~
  does not seem to be needed - out boot/boot2 should boot on any provider after #480 (which is actually a prerequisite for booting on all providers)
- [x] https://github.com/nanovms/nanos/issues/275 - boot to GCE
  - [x] virtio-scsi: https://cloud.google.com/compute/docs/images/building-custom-os
- [x] https://github.com/nanovms/nanos/issues/276 - boot on AWS
  - [x] Firecracker - https://groups.google.com/forum/#!topic/osv-dev/BAdpXmjtC24
     **supports virtio-net and virtio-blk via mmio - needs virtio mmio support**
     - [x] eval firecracker && see what happens - https://github.com/nanovms/nanos/issues/483
  - [ ] AWS C5:
    - [ ] [nvme storage driver](https://github.com/nanovms/nanos/issues/1316)
    - [ ] [ena network driver](https://github.com/nanovms/nanos/issues/1233)
  - [x] AWS T2
     - [x] xen-platform block driver
     - [x] IDE storage driver - https://github.com/nanovms/nanos/pull/871
     - [x] xen-platform network driver
  
- [x] [boot to digital ocean](https://github.com/nanovms/nanos/issues/614)
- [ ] [boot to linode](https://github.com/nanovms/nanos/issues/682)

- [ ] [boot to alicloud](https://github.com/nanovms/nanos/issues/802)

- [x] https://github.com/nanovms/nanos/issues/1118 - vsphere
   - [x] vmxnet network driver
   - [x] pvscsi driver
It's also worth investigating deploying to these as well:

- [x] openstack
   openstack is KVM-based
https://github.com/nanovms/nanos/issues/1225
   **supports virtio-net and virtio-blk - should just work**
- [ ] virtualbox
   - [ ] IDE or SCSI storage driver (does not support virtio-blk)
- [ ] https://github.com/nanovms/nanos/issues/484 - azure (Hyper-V)
   - [x] VMBus support
   - [ ] VMBus storage driver
   - [x] VMBus network driver

so to clarify - whatever is made should be extensible enough to satisfy these - we can have a default whatever that is but also want/need the capability to switch out deploy targets as needed

https://devel.unikernel.org/t/unikernels-on-clouds-just-a-mirage/227
